/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package battleship;

import textInterface.InputHandler;
import textInterface.TextInterfaceController;
import textInterface.TextInterfaceView;
import textInterface.View;

public class App {
    public static void main(String[] args) {
//        TwoPlayerGame game = new TwoPlayerGame(10);
        TextInterfaceView view = new TextInterfaceView();
//        TextInterfaceController controller = new TextInterfaceController(game, view);
        TextInterfaceController controller = new TextInterfaceController(view);
        view.setInputHandler(controller);
        controller.start();
    }
}
